import { FlashCard } from './flashcard.model';

export const FLASHCARDS: FlashCard[] = [
  { id: 1, question: "A", answer: null, visible: true },
  { id: 2, question: "B", answer: null, visible: false },
  { id: 3, question: "C", answer: null, visible: false },
  { id: 4, question: "D", answer: null, visible: false },
  { id: 5, question: "E", answer: null, visible: false },
  { id: 6, question: "F", answer: null, visible: false },
  { id: 7, question: "G", answer: null, visible: false },
  { id: 8, question: "H", answer: null, visible: false },
  { id: 9, question: "I", answer: null, visible: false },
  { id: 10, question: "J", answer: null, visible: false },
  { id: 11, question: "K", answer: null, visible: false },
  { id: 12, question: "L", answer: null, visible: false },
  { id: 13, question: "M", answer: null, visible: false },
  { id: 14, question: "N", answer: null, visible: false },
  { id: 15, question: "O", answer: null, visible: false },
  { id: 16, question: "P", answer: null, visible: false },
  { id: 17, question: "Q", answer: null, visible: false },
  { id: 18, question: "R", answer: null, visible: false },
  { id: 19, question: "S", answer: null, visible: false },
  { id: 20, question: "T", answer: null, visible: false },
  { id: 21, question: "U", answer: null, visible: false },
  { id: 22, question: "V", answer: null, visible: false },
  { id: 23, question: "W", answer: null, visible: false },
  { id: 24, question: "X", answer: null, visible: false },
  { id: 25, question: "Y", answer: null, visible: false },
  { id: 26, question: "Z", answer: null, visible: false }
];